version: '3.5'
services:
  nginx: 
    image: nginx:latest
    container_name: brewit_nginx
    # volumes:
    #   - ./nginx:/
    ports:
      - 80:80
      - 443:443
    networks:
      - brewit_network
  postgres:
    container_name: brewit_postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
    # volumes:
    #    - ./postgres/postgresql.conf:/data/postgres/
    ports:
      - "5432:5432"
    networks:
      - brewit_network
    restart: unless-stopped
  pgadmin:
    container_name: brewit_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    # volumes:
    #    - ./pgadmin/:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT}:80"
    networks:
      - brewit_network
    restart: unless-stopped
  tomcat:
    image: tomcat
    container_name: brewit_tomcat
    ports: 
      - "${TOMCAT_PORT}:8080"
    networks:
      - brewit_network
    volumes:
      - ./tomcat/hello-world.war:/usr/local/tomcat/webapps/ROOT.war
      # - ./tomcat/DockerExample:/usr/local/tomcat/webapps/ROOT


networks:
  brewit_network:
    driver: bridge